version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: rodepush-postgres
    environment:
      POSTGRES_DB: rodepush_test
      POSTGRES_USER: rodepush
      POSTGRES_PASSWORD: rodepush123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U rodepush -d rodepush_test']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rodepush-redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
